coverage:
  precision: 2
  round: down
  range: "90...100"

ignore:
  - "server/src/main/java/nl/altindag/server/App.java"
  - "client/src/main/java/nl/altindag/client/CucumberConfiguration.java"
  - "client/src/main/java/nl/altindag/client/TestScenario.java"
  - "client/src/main/java/nl/altindag/client/ClientException.java"
  - "client/src/main/java/nl/altindag/client/ClientRunner.java"
